name: npm publish

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          registry-url: https://registry.npmjs.org/

      - run: yarn install --immutable && yarn compile

      - run: npm publish --provenance
